# permissions for end users to view views.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-viewer-role
rules:
- apiGroups:
  - qapla.42nerds.com
  resources:
  - views
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qapla.42nerds.com
  resources:
  - views/status
  verbs:
  - get
