# permissions for end users to edit views.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-editor-role
rules:
- apiGroups:
  - qapla.42nerds.com
  resources:
  - views
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qapla.42nerds.com
  resources:
  - views/status
  verbs:
  - get
